# Generated by Django 4.2.9 on 2024-03-14 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ALIMENTATION', 'Alimentation'), ('LOISIRS', 'Loisirs'), ('TRANSPORT', 'Transport'), ('LOGEMENT', 'Logement'), ('SANTE', 'Santé'), ('EDUCATION', 'Éducation'), ('DIVERS', 'Divers'), ('EPARGNE', 'Épargne'), ('INVESTISSEMENTS', 'Investissements'), ('ASSURANCES', 'Assurances'), ('UTILITES', 'Utilités'), ('VETEMENTS', 'Vêtements'), ('CADEAUX', 'Cadeaux'), ('VOYAGES', 'Voyages'), ('REMBOURSEMENT', 'Remboursement'), ('BEAUTE', 'Beauté'), ('SPORT', 'Sport'), ('TECHNOLOGIE', 'Technologie'), ('RESTAURANTS', 'Restaurants'), ('ANIMAUX', 'Animaux'), ('LOYER', 'Loyer')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('DEPENSE', 'Dépense'), ('REVENU', 'Revenu')], default='DEPENSE', max_length=7)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
