# Generated by Django 4.2.9 on 2024-03-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_recurringexpense_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('ALIMENTATION', 'Alimentation'), ('LOISIRS', 'Loisirs'), ('TRANSPORT', 'Transport'), ('LOGEMENT', 'Logement'), ('SANTE', 'Santé'), ('EDUCATION', 'Éducation'), ('DIVERS', 'Divers'), ('EPARGNE', 'Épargne'), ('INVESTISSEMENTS', 'Investissements'), ('ASSURANCES', 'Assurances'), ('UTILITES', 'Utilités'), ('VETEMENTS', 'Vêtements'), ('CADEAUX', 'Cadeaux'), ('VOYAGES', 'Voyages'), ('REMBOURSEMENT', 'Remboursement'), ('BEAUTE', 'Beauté'), ('SPORT', 'Sport'), ('TECHNOLOGIE', 'Technologie'), ('RESTAURANTS', 'Restaurants'), ('ANIMAUX', 'Animaux'), ('LOYER', 'Loyer')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='category',
            field=models.CharField(choices=[('ALIMENTATION', 'Alimentation'), ('LOISIRS', 'Loisirs'), ('TRANSPORT', 'Transport'), ('LOGEMENT', 'Logement'), ('SANTE', 'Santé'), ('EDUCATION', 'Éducation'), ('DIVERS', 'Divers'), ('EPARGNE', 'Épargne'), ('INVESTISSEMENTS', 'Investissements'), ('ASSURANCES', 'Assurances'), ('UTILITES', 'Utilités'), ('VETEMENTS', 'Vêtements'), ('CADEAUX', 'Cadeaux'), ('VOYAGES', 'Voyages'), ('REMBOURSEMENT', 'Remboursement'), ('BEAUTE', 'Beauté'), ('SPORT', 'Sport'), ('TECHNOLOGIE', 'Technologie'), ('RESTAURANTS', 'Restaurants'), ('ANIMAUX', 'Animaux'), ('LOYER', 'Loyer')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('ALIMENTATION', 'Alimentation'), ('LOISIRS', 'Loisirs'), ('TRANSPORT', 'Transport'), ('LOGEMENT', 'Logement'), ('SANTE', 'Santé'), ('EDUCATION', 'Éducation'), ('DIVERS', 'Divers'), ('EPARGNE', 'Épargne'), ('INVESTISSEMENTS', 'Investissements'), ('ASSURANCES', 'Assurances'), ('UTILITES', 'Utilités'), ('VETEMENTS', 'Vêtements'), ('CADEAUX', 'Cadeaux'), ('VOYAGES', 'Voyages'), ('REMBOURSEMENT', 'Remboursement'), ('BEAUTE', 'Beauté'), ('SPORT', 'Sport'), ('TECHNOLOGIE', 'Technologie'), ('RESTAURANTS', 'Restaurants'), ('ANIMAUX', 'Animaux'), ('LOYER', 'Loyer')], max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
